### ISSUE TITLE
Segfault in Binder after running compiled query

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#961] opened 2020-06-14 13:40 UTC
**Summary:**
There are appears to be an issue with exception handling after a query has been compiled to native code. I've seen this on Ubuntu 18.04 and 20.04 both locally and on EC2. I cannot reproduce the issue on macOS.

**Steps to reproduce:**
I found this while benchmarking TPC-C that throws an expected exception in the Binder, but can reproduce it more succinctly.
- Change [this line](https://github.com/cmu-db/terrier/blob/b765cf22b8afb63e2e44e43b8af578fb2056b6b1/src/traffic_cop/traffic_cop.cpp#L339) to `ExecutionMode::Compiled` to force compilation to machine code rather than TPL interpretation of queries.
- Build the `tpl` and `terrier` targets. The former is necessary to generate the bytecode file. We should add it as a proper dependency of `terrier` in the future because if you forget to build `tpl` first you get a segfault on the server.
```
matt@Matts-MBP ~ % psql -h 172.16.226.131 -p 15721 -d terrier
psql (12.3, server 9.5devel)
Type "help" for help.

terrier=# create table foo (id int);
CREATE TABLE
Time: 4.249 ms
terrier=# select bar from foo;  --throws exception just fine because no DML yet
ERROR:  binding failed
Time: 1.340 ms
terrier=# insert into foo values (1),(2),(3); --DML query that invoked and linked in LLVM
INSERT 0 3
Time: 299.403 ms
terrier=# select bar from foo; --segfault on throwing exception
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 6842.192 ms (00:06.842)
!> 
```

My suspicion is that LLVM links in incompatible exception handling code after compilation, either due to a version mismatch or some other issue. I tried changing from building `terrier` with GCC to the same version of clang that `tpl` uses to generate the bytecode handlers but it didn't help.

**Comment by gonzalezjo** [comment] 2020-06-14 15:24
Initial impressions before I go back to cramming for a midterm.

Some very confused debugging later, and I'm pretty sure that the issue is on LLVM 8's end. This may or may not be fixed in newer versions.

LLVM seemingly creates an exception handling frame when you call into LLVM code. If you throw an exception and LLVM 8 ends up having to abort from a function--at least in our case--it will may not properly deregister its exception handling frame. Valgrind might be losing track here, or I may be missing something, but I *believe* (even though Valgrind cannot find a relevant "recent free") LLVM is also freeing the exception handling frame. So there could be some UAF-related corruption here, but it's hard to tell.


Regardless, the contents of the exception handling frame are no longer relevant to any executing code after the JITed code aborts, even though the frame is still registered. The next time an exception is thrown (in this case, it happens in `schema.h:GetColumn`) libunwind tries to traverse the exception handling frames. But the exception thrown by the JIT has the frames corrupted, and we end up segfaulting in libunwind.


Supporting this idea is that the issue isn't reproducible when using Apple's fork of LLVM and Clang, which is considerably more up to date.

**Comment by gonzalezjo** [comment] 2020-06-14 16:43
So this is absolutely an LLVM issue. A known one, at that: http://llvm.1065342.n5.nabble.com/llvm-dev-New-ORC-v2-LLJIT-global-variables-tp130449p130629.html 

I don't see any obvious workarounds besides patching LLVM or managing exception frames ourselves. Neither of which seem practical, trivial, or portable.

It is, in fact, a linker error. It's just not the trivial kind. RuntimeDyld (which is implemented differently for for MachO/MacOS binaries than it is for Linux/ELF binaries) has really poor exception handling frame support. It's completely broken on master, actually.

LLVM is ditching RuntimeDyld for JITLink, but they only JUST got preliminary elf support working in a dev branch. I wouldn't be surprised if we didn't see it until May. As of right now, we can only use it for MacOS, which doesn't have this problem anyway.

**Comment by gonzalezjo** [comment] 2020-06-14 17:49
...and, fixed? https://github.com/gonzalezjo/terrier/commit/cbddc669cb7af85bb638fa1b0fd24d0270dd8f2b


Fairly anticlimactic solution if that works for others and doesn't introduce any new bugs.

**Closed** 2020-06-15 18:04 UTC
Labels: bug
