### ISSUE TITLE
Bogus performance regression on Jenkins

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#211] opened 2018-10-14 21:24 UTC
Since we changed around thread number in #200. Example failure: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-207/27/pipeline

I guess we either didn't notice or didn't fix this because of  #193
 
I've verified both locally and on dev4 that these seemingly large deltas result from changes in the benchmark setup rather than code performance regression. We might still want these number changes, and we just need to reset the reference numbers on Jenkins.

**Comment by mbutrovich** [comment] 2018-10-14 22:57
@pervazea discussed it at the time #200 went in. We have bigger issues with Jenkins right now.

**Comment by tli2** [comment] 2018-10-15 14:44
Is this the Jenkins trigger not working issue?

**Comment by crd477** [comment] 2018-10-15 14:51
Yes.  It never worked as intended for new pull requests and I'm about to back it out.  In the meantime, I re-enabled the periodic repository scan in the Jenkins configuration to pick this up.

**Comment by crd477** [comment] 2018-10-15 15:05
@pervazea or @apavlo, if you have admin privileges for the terrier Github project, could you please add a webhook with a payload URL of http://jenkins.db.cs.cmu.edu:8080/github-webhook/  ?  All of the other values can stay at their defaults.

**Comment by apavlo** [comment] 2018-10-15 15:39
@crd477 Done!

**Comment by mbutrovich** [comment] 2018-10-19 17:32
Fixed in #218

**Closed by mbutrovich** 2018-10-19 17:32 UTC
Labels: bug, infrastructure
