### ISSUE TITLE
Inserting into table with out-of-order qualified columns is ignored

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#729] opened 2020-02-01 17:28 UTC
```
terrier=# CREATE TABLE tbl (c1 int not null primary key, c2 int, c3 int);
CREATE TABLE
terrier=# insert into tbl (c3, c1, c2) VALUES (3, 1, 2);
INSERT 0 1
terrier=# SELECT * FROM tbl;
 c1 | c2 | c3 
----+----+----
  3 |  1 |  2
(1 row)
terrier=# 
```

**Comment by apavlo** [comment] 2020-02-04 17:29
@17zhangw suspects that the problem is in the codegen layer.

**Comment by apavlo** [comment] 2020-08-27 23:03
Fixed in #758

**Closed by apavlo** 2020-08-27 23:03 UTC
Labels: bug
